[tool.poetry]
name = "twitter-b2bit"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "twitter_b2bit"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.1"
django-rest = "^0.8.7"
pillow = "^9.5.0"
django-stubs = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
