# Generated by Django 4.2.1 on 2023-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
