# Generated by Django 4.2.1 on 2023-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_data_nascimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
