# Generated by Django 4.2.1 on 2023-05-25 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_profile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nome",
            new_name="username",
        ),
    ]
