name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    env:
      DB_ENGINE=django.db.backends.sqlite3
      DB_NAME=db.sqlite3
      SECRET_KEY=secret
      JWT_SECRET=secret
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black
      - run: pip install pytest-django
      - run: pip install -r requirements.txt # install all our dependencies for the project
      - run: pytest -s -x --cov=core --cov=menu --cov=user -vv
      - run: black --check .

